name: "Successful Deployment Notifications"
description: "Action to send Slack notifications when the deployment has succeed."
inputs:
  environment:
    description: "Environment which the workflow is running on."
    required: false
    default: ""
  project:
    description: "Name of the project."
    required: true
  slack-bot-token:
    description: "Slack Bot Token to send notifications to channels."
    required: true
  github-run-id:
    description: "Github Actions Run ID of the workflow."
    required: true
runs:
  using: "composite"
  steps:
    - name: Send success notification to Slack
      id: slack
      uses: slackapi/slack-github-action@v1.26.0
      with:
        channel-id: "curves-eng-feed"
        payload: |
          {
            "blocks": [
              {
                "type": "image",
                "image_url": "https://www.freeiconspng.com/uploads/success-icon-11.png",
                "alt_text": "success"
              },
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "Successful Deployment 🚀 ${{ inputs.project }} 🏗 ${{ inputs.environment }}"
                }
              },
              {
                "type": "rich_text",
                "elements": [
                  {
                    "type": "rich_text_section",
                    "elements": [
                      {
                        "type": "text",
                        "text": "A new version has been successfully deployed. ✅"
                      }
                    ]
                  }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Go to Workflow"
                    },
                    "url": "https://github.com/roll-network/uniswap-frontend/actions/runs/${{ inputs.github-run-id }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
